markdown: rdiscount
permalink: /:title/
url: http://codingcoder.com
name: Yonsm.NET
author: Yonsm
qq: 546662815
email: happyjiahan@gmail.com
duoshuo: happyjiahan
weibo: 1885061391
github: Yonsm
pygments: true
safe: true
paginate: 20
about: "分享 记录"
