markdown: rdiscount
permalink: /:title/
url: http://blog.codingcoder.com
name: 放慢脚步
author: happyjiahan
qq: 546662815
email: happyjiahan@gmail.com
duoshuo: blog-codingcoder 
cnzz: 1000261657
weibo: 1900599231
github: happyjiahan
pygments: true
safe: true
paginate: 20
about: "分享 记录"
