markdown: rdiscount
permalink: /:title/
url: codingcoder.com
name: codingcoder blog
author: potu
qq: 546662815
email: happyjiahan@gmail.com 
duoshuo:happyjiahan 
github: happyjiahan 
pygments: true
safe: true
paginate: 2
about: "分享 记录 反思 交友"
